# Generated by Django 4.1 on 2024-07-06 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npost_model',
            name='user_likes',
            field=models.ManyToManyField(related_name='viewers_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
